In [1]:
import pandas as pd

https://data-make.tistory.com/139 그룹연산 <br>
https://m.blog.naver.com/PostView.nhn?blogId=bosongmoon&logNo=221574787121&proxyReferer=https%3A%2F%2Fwww.google.com%2F 판다스 기초 <br>
https://dojang.io/mod/page/view.php?id=2459 그래프 그리기

In [2]:
data = pd.read_excel("C:/Marketing_project/sh/라면데이터.xlsx")

In [3]:
data.head()

,채널,FACT,제품명,제조사,브랜드,서브 브랜드,포장형태,면 종류,JAN17,FEB17,...,MAR19,APR19,MAY19,JUN19,JUL19,AUG19,SEP19,OCT19,NOV19,DEC19
0,전국,판매액,A 제조사 추추라면 노브랜드 봉지,A 제조사,추추라면,노브랜드,봉지,유탕면,11744.7,10788.2,...,10449.9,9024.43,9563.04,9092.26,9435.4,9724.52,9438.88,10799.2,9213.99,9937.66
1,전국,판매액,A 제조사 짜장라면 노브랜드 봉지,A 제조사,짜장라면,노브랜드,봉지,유탕면,4380.98,4733.58,...,6850.06,7048.65,5855.35,6137.5,6619.79,6751.39,6562.12,6201.79,6242.24,5890.04
2,전국,판매액,A 제조사 맛라면 노브랜드 봉지,A 제조사,맛라면,노브랜드,봉지,유탕면,4949.5,4626.35,...,4269.52,3835.04,3833.66,4651.44,3678.67,4318.06,4812.97,4486.84,4476.71,5384.01
3,전국,판매액,C 제조사 강라면 매운맛 봉지,C 제조사,강라면,매운맛,봉지,유탕면,4286.81,3925.16,...,4595.98,4578.35,4295.45,4061.11,4172.93,4274.73,4072.87,4071.65,4018.61,4525.94
4,전국,판매액,A 제조사 우리라면 얼큰한맛 봉지,A 제조사,우리라면,얼큰한맛,봉지,유탕면,4883.79,4012.39,...,3208.46,2506.36,2967.5,3123.96,3127.75,3309.08,3326.33,3519.37,3863.74,3817.03

In [4]:
data = data[data["채널"]!="전국"]
data

,채널,FACT,제품명,제조사,브랜드,서브 브랜드,포장형태,면 종류,JAN17,FEB17,...,MAR19,APR19,MAY19,JUN19,JUL19,AUG19,SEP19,OCT19,NOV19,DEC19
1856,할인점,판매액,A 제조사 추추라면 노브랜드 봉지,A 제조사,추추라면,노브랜드,봉지,유탕면,2769.14,2373.54,...,2839.28,1908.15,1907.44,2059.93,2452.86,2485.75,1946.05,3016.61,1944.07,2052.48
1857,할인점,판매액,A 제조사 짜장라면 노브랜드 봉지,A 제조사,짜장라면,노브랜드,봉지,유탕면,1318.9,1496.86,...,1919.45,2165.57,1911.38,1900.45,2076.98,2141.11,2219.31,2013.97,2041.52,1778.44
1858,할인점,판매액,A 제조사 맛라면 노브랜드 봉지,A 제조사,맛라면,노브랜드,봉지,유탕면,1341.23,1220.51,...,923.574,839.274,982.53,1336.46,803.862,1162.68,1152.31,974.214,1099.85,1378.93
1859,할인점,판매액,C 제조사 강라면 매운맛 봉지,C 제조사,강라면,매운맛,봉지,유탕면,1236.66,1191.45,...,1373.32,1438.78,1213.99,1195.61,1242.34,1402.44,1212.81,1099.52,1181.41,1222.35
1860,할인점,판매액,A 제조사 우리라면 얼큰한맛 봉지,A 제조사,우리라면,얼큰한맛,봉지,유탕면,1790.39,1317.92,...,851.28,525.48,767.646,890.85,867.444,949.788,942.558,965.076,1223.35,1053.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12987,개인소형+일반수퍼,L/KG당 판매가격,D 제조사 기타 기타 봉지,D 제조사,기타,기타,봉지,유탕면,NaN,965.699,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12988,개인소형+일반수퍼,L/KG당 판매가격,D 제조사 기타 기타 봉지,D 제조사,기타,기타,봉지,유탕면,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12989,개인소형+일반수퍼,L/KG당 판매가격,D 제조사 기타 기타 봉지,D 제조사,기타,기타,봉지,유탕면,NaN,NaN,...,ERR,1309.52,1315.79,1344.26,1352.94,1300,1333.33,2000,ERR,NaN
12990,개인소형+일반수퍼,L/KG당 판매가격,D 제조사 기타 기타 봉지,D 제조사,기타,기타,봉지,유탕면,NaN,NaN,...,1493.33,ERR,ERR,1363.64,1455.36,1500,NaN,NaN,NaN,NaN
12991,개인소형+일반수퍼,L/KG당 판매가격,D 제조사 기타 기타 봉지,D 제조사,기타,기타,봉지,유탕면,NaN,NaN,...,NaN,1200,1310.81,1325.47,1056.12,1102.77,1203.12,1297.3,ERR,NaN

In [110]:
data['채널'].unique()

array(['할인점', '체인대형', '조합마트', '편의점', '개인대형', '개인소형+일반수퍼'], dtype=object)

In [111]:
import numpy as np

data['판매총액'] = 0
data['판매총액'] = data.loc[:, "JAN17":"DEC17"].fillna(0).replace("ERR", 0).apply(np.sum, axis=1)
data['판매총액'].head()

1856    33343.308
1857    16623.810
1858    15195.462
1860    12236.124
1862    10186.644
Name: 판매총액, dtype: float64

In [112]:
data['FACT'].unique()

array(['판매액', '판매량 (UNIT)', 'WD SELLING DIST', 'L/KG당 판매가격'], dtype=object)

In [113]:
# 판매액 
sales_rate_idx = data['FACT'] == '판매액'

# 판매량
sales_amount_idx = data['FACT'] == '판매량 (UNIT)'

In [69]:
# 채널별 
sales_rate = data[sales_rate_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("17 채널별 판매액")
print("="*10)
print(sales_rate.sum())

sales_amount = data[sales_amount_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("17 채널별 판매량")
print("="*10)
print(sales_amount.sum())

==========
17 채널별 판매액
==========
채널
개인대형          228067.524
개인소형+일반수퍼     141579.720
전국           1228200.060
조합마트           93634.926
체인대형          131538.822
편의점           330241.854
할인점           303137.190
Name: 판매총액, dtype: float64

==========
17 채널별 판매량
==========
채널
개인대형          304102.434
개인소형+일반수퍼     167347.182
전국           1575429.360
조합마트          135137.262
체인대형          195921.138
편의점           311398.794
할인점           461522.784
Name: 판매총액, dtype: float64

In [114]:
sales_sum_17 = sales_rate.sum()
sales_amount_17 = sales_amount.sum()
sales_amount_17

채널
개인대형         3.674958e+06
개인소형+일반수퍼    3.416050e+06
전국           1.589438e+06
조합마트         2.957174e+06
체인대형         3.162805e+06
편의점          3.819799e+06
할인점          3.555859e+06
Name: 판매총액, dtype: float64

In [115]:
import numpy as np

data['판매총액'] = 0
data['판매총액'] = data.loc[:, "JAN18":"DEC18"].fillna(0).replace("ERR", 0).apply(np.sum, axis=1)
data['판매총액'].head()

# 판매액 
sales_rate_idx = data['FACT'] == '판매액' 

# 판매량
sales_amount_idx = data['FACT'] == '판매량 (UNIT)'

# 채널별 
sales_rate = data[sales_rate_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("18 채널별 판매액")
print("="*10)
print(sales_rate.sum())

sales_amount = data[sales_amount_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("18 채널별 판매량")
print("="*10)
print(sales_amount.sum())

==========
18 채널별 판매액
==========
채널
개인대형         127613.934
개인소형+일반수퍼     98352.654
조합마트          56284.728
체인대형          70430.802
편의점          145712.442
할인점          164862.420
Name: 판매총액, dtype: float64

==========
18 채널별 판매량
==========
채널
개인대형         159717.576
개인소형+일반수퍼    113348.982
조합마트          77385.690
체인대형          98791.848
편의점          144907.518
할인점          233904.900
Name: 판매총액, dtype: float64

In [116]:
sales_sum_18 = sales_rate.sum()
sales_amount_18 = sales_amount.sum()

In [117]:
import numpy as np

data['판매총액'] = 0
data['판매총액'] = data.loc[:, "JAN19":"DEC19"].fillna(0).replace("ERR", 0).apply(np.sum, axis=1)
data['판매총액'].head()

# 판매액 
sales_rate_idx = data['FACT'] == '판매액'

# 판매량
sales_amount_idx = data['FACT'] == '판매량 (UNIT)'

# 채널별 
sales_rate = data[sales_rate_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("19 채널별 판매액")
print("="*10)
print(sales_rate.sum())

sales_amount = data[sales_amount_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("19 채널별 판매량")
print("="*10)
print(sales_amount.sum())

==========
19 채널별 판매액
==========
채널
개인대형         124183.806
개인소형+일반수퍼     86145.540
조합마트          56663.310
체인대형          72174.390
편의점          147909.246
할인점          165314.928
Name: 판매총액, dtype: float64

==========
19 채널별 판매량
==========
채널
개인대형         156386.124
개인소형+일반수퍼     99792.696
조합마트          79195.014
체인대형         102234.558
편의점          149211.582
할인점          240405.234
Name: 판매총액, dtype: float64

In [118]:
sales_sum_19 = sales_rate.sum()
sales_amount_19 = sales_amount.sum()

In [119]:
%matplotlib inline
import pandas as pd                # 데이터를 저장하고 처리하는 패키지
import matplotlib as mpl           # 그래프를 그리는 패키지
import matplotlib.pyplot as plt    # 그래프를 그리는 패키지