In [1]:
import pandas as pd

data = pd.read_excel("exam.xlsx")
data.head()

   채널 FACT                 제품명    제조사  ...    SEP19    OCT19    NOV19    DEC19
0  전국  판매액  A 제조사 추추라면 노브랜드 봉지  A 제조사  ...  9438.88  10799.2  9213.99  9937.66
1  전국  판매액  A 제조사 짜장라면 노브랜드 봉지  A 제조사  ...  6562.12  6201.79  6242.24  5890.04
2  전국  판매액   A 제조사 맛라면 노브랜드 봉지  A 제조사  ...  4812.97  4486.84  4476.71  5384.01
3  전국  판매액    C 제조사 강라면 매운맛 봉지  C 제조사  ...  4072.87  4071.65  4018.61  4525.94
4  전국  판매액  A 제조사 우리라면 얼큰한맛 봉지  A 제조사  ...  3326.33  3519.37  3863.74  3817.03

[5 rows x 44 columns]

In [55]:
data['판매총액'].iloc[1]

0

In [66]:
data.loc[:, "JAN17":"DEC19"].fillna(0).replace("ERR", 0).apply(np.sum, axis=1)

0        386565.684000
1        202286.280000
2        165409.512000
3        155893.260000
4        125761.740000
             ...
12987     10957.755361
12988     16486.448222
12989     25925.931535
12990      7310.162338
12991      8495.594053
Length: 12992, dtype: float64

In [60]:
import numpy as np

data['판매총액'] = 0
data['판매총액'] = data.loc[:, "JAN17":"DEC19"].fillna(0).replace("ERR", 0).apply(np.sum, axis=1)
data['판매총액'].head()

0    386565.684
1    202286.280
2    165409.512
3    155893.260
4    125761.740
Name: 판매총액, dtype: float64

In [7]:
data['채널'].unique()

array(['전국', '할인점', '체인대형', '조합마트', '편의점', '개인대형', '개인소형+일반수퍼'],
      dtype=object)

In [68]:
data['FACT'].unique()

array(['판매액', '판매량 (UNIT)', 'WD SELLING DIST', 'L/KG당 판매가격'], dtype=object)

In [70]:
# 판매액 
sales_rate_idx = data['FACT'] == '판매액'

# 판매량
sales_amount_idx = data['FACT'] == '판매량 (UNIT)'

In [74]:
# 채널별 
sales_rate = data[sales_rate_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("채널별 판매액")
print("="*10)
print(sales_rate.sum())

sales_amount = data[sales_amount_idx]['판매총액'].groupby(data['채널'])
print()
print("="*10)
print("채널별 판매량")
print("="*10)
print(sales_amount.sum())

==========
채널별 판매액
==========
채널
개인대형          697663.290
개인소형+일반수퍼     479374.530
전국           3717602.340
조합마트          278360.976
체인대형          395337.354
편의점           955003.920
할인점           911862.180
Name: 판매총액, dtype: float64

==========
채널별 판매량
==========
채널
개인대형          927121.350
개인소형+일반수퍼     564090.858
전국           4728359.190
조합마트          396514.716
체인대형          585250.998
편의점           894926.154
할인점          1360455.096
Name: 판매총액, dtype: float64

In [79]:
# 채널별 제조사별
sales_rate = data[sales_rate_idx]['판매총액'].groupby([data['채널'], data['제조사']])
print()
print("="*10)
print("채널별 판매액")
print("="*10)
print(sales_rate.sum())

sales_amount = data[sales_amount_idx]['판매총액'].groupby([data['채널'], data['제조사']])
print()
print("="*10)
print("채널별 판매량")
print("="*10)
print(sales_amount.sum())

==========
채널별 판매액
==========
채널         제조사
개인대형       A 제조사     382305.606
           B 제조사      90305.244
           C 제조사     156271.176
           D 제조사      68773.374
           PB             7.890
개인소형+일반수퍼  A 제조사     296427.222
           B 제조사      57717.432
           C 제조사      77581.440
           D 제조사      47641.254
           PB             7.182
전국         A 제조사    1989169.566
           B 제조사     433042.350
           C 제조사     857586.516
           D 제조사     348709.302
           PB         89094.606
조합마트       A 제조사     170153.694
           B 제조사      30816.162
           C 제조사      56621.094
           D 제조사      20680.638
           PB            89.388
체인대형       A 제조사     213524.466
           B 제조사      35539.932
           C 제조사     109195.344
           D 제조사      33193.842
           PB          3883.770
편의점        A 제조사     432176.232
           B 제조사     134166.204
           C 제조사     215505.822
           D 제조사      99015.252
           PB         74140.410
할인점        A 제조사     494582.160
           B 제조사      84497.124
           C 제조사     242411.982
           D 제조사      79404.876
           PB         10966.038
Name: 판매총액, dtype: float64

==========
채널별 판매량
==========
채널         제조사
개인대형       A 제조사     478366.914
           B 제조사     115152.402
           C 제조사     252490.380
           D 제조사      81105.696
           PB             5.958
개인소형+일반수퍼  A 제조사     341372.202
           B 제조사      68110.992
           C 제조사     103204.284
           D 제조사      51398.400
           PB             4.980
전국         A 제조사    2484968.910
           B 제조사     509902.494
           C 제조사    1243416.036
           D 제조사     413427.930
           PB         76643.820
조합마트       A 제조사     234330.792
           B 제조사      44791.188
           C 제조사      91575.126
           D 제조사      25715.358
           PB           102.252
체인대형       A 제조사     297809.070
           B 제조사      48371.082
           C 제조사     190588.836
           D 제조사      45000.426
           PB          3481.584
편의점        A 제조사     431328.546
           B 제조사     105015.036
           C 제조사     207623.550
           D 제조사      97010.004
           PB         53949.018
할인점        A 제조사     701761.506
           B 제조사     128461.818
           C 제조사     397933.704
           D 제조사     113198.016
           PB         19100.052
Name: 판매총액, dtype: float64